name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
      - master
    types:
      - closed

jobs:
  publish-release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Extract version from branch name (for release branches)
        if: startsWith(github.event.pull_request.head.ref, 'release/')
        run: |
          tag=${{ github.ref }}
          version=${tag#release-}
          echo "::set-output name=version::$version" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Create release
        uses: thomaseizinger/create-release@1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          tag_name: ${{ env.version }}
          name: ${{ env.version }}
          draft: false
          prerelease: false
